# Generated by Django 6.0.6 on 2026-06-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('pengarang', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=50)),
                ('penerbit', models.CharField(max_length=255)),
                ('tahun_terbit', models.IntegerField()),
                ('rak', models.CharField(max_length=50)),
                ('stok', models.IntegerField()),
                ('deskripsi', models.TextField()),
            ],
            options={
                'db_table': 'buku',
            },
        ),
    ]
